# Generated by Django 4.2.7 on 2023-11-03 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0002_calidad_establecimiento_categoria_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanburgerapp.establecimiento'),
        ),
    ]
