# Generated by Django 4.2.7 on 2023-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sanburgerapp', '0004_usuarios_contrasena_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contrasena',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='correoUsuario', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default='usuario', max_length=255, unique=True),
        ),
    ]
