# Generated by Django 4.2.7 on 2023-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0006_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='correoUsuario', max_length=254, unique=True)),
                ('username', models.CharField(default='usuario', max_length=255, unique=True)),
                ('password', models.CharField(default='contrasena', max_length=40)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('numero_tarjeta', models.IntegerField()),
                ('titular_tarjeta', models.CharField(max_length=30)),
                ('caducidad_tarjeta', models.DateField()),
                ('cvv_tarjeta', models.IntegerField()),
                ('password_tarjeta', models.CharField(max_length=20)),
            ],
        ),
    ]
