# Generated by Django 4.2.7 on 2023-11-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0007_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
