# Generated by Django 4.2.7 on 2023-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0013_alter_usuarios_email_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
    ]
