# Generated by Django 4.2.7 on 2023-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0016_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='picture',
            field=models.ImageField(default=None, upload_to='static/IMAGES/products/'),
        ),
    ]
