# Generated by Django 4.2.7 on 2023-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0023_remove_producto_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/IMAGES/products/'),
        ),
    ]
