# Generated by Django 4.2.7 on 2023-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0025_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
