# Generated by Django 4.2.7 on 2023-12-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanburgerapp', '0026_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(default='sin correo', max_length=30),
        ),
    ]
